ifneq (,$(filter seeeduino_xiao-nRF52840_battery,$(USEMODULE))) # if module in USEMODULE

FEATURES_REQUIRED += cpp
FEATURES_REQUIRED += periph_adc
FEATURES_REQUIRED += seeeduino_xiao-nRF52840_battery_pins
USEMODULE += shell

endif
